- hosts: localhost


  vars:
    subscription_id: 695f969d-2418-491f-a6b3-bd0bf0c7cffb
    resource_group: openenv-njmbx

  tasks:
    - name: get some info
      azure.azcollection.azure_rm_subscription_info:
        all: true
      register: azure_subscription_info

    - name: Create an array of subscription IDs
      ansible.builtin.set_fact:
        subscription_ids: "{{ azure_subscription_info.subscriptions | map(attribute='subscription_id') | list }}"

    - ansible.builtin.debug:
        msg: "Subscription IDs: {{ subscription_ids }}"

    # - name: get some info
    #   azure.azcollection.azure_rm_subscription_info:
    #     subscription_id: "{{ subscription_ids }}"
    #   register: azure_subscription_info

    - name: Query all the resources in the resource group
      azure.azcollection.azure_rm_resourcegroup_info:
        subscription_id: "{{ item }}"
      register: azure_resource_groups_info
      loop: "{{ subscription_ids }}"

    - ansible.builtin.debug:
        var: azure_resource_groups_info
    
    - ansible.builtin.debug:
        msg: "{{ azure_resource_groups_info.results[0].resourcegroups}}"


    - name: Get all resource groups in the subscription
      ansible.builtin.set_fact:
        resource_groups: "{{ azure_resource_groups_info.results[0].resourcegroups | map(attribute='name') | list }}"

    - name: create resource dictionary
      ansible.builtin.set_fact:
        resource_dict: "{{ resource_dict | default({}) | combine({item: azure_resource_groups_info.resourcegroups[item]}) }}"
      loop: "{{ resource_groups }}"

    - name: Combine subscription IDs and resource groups into dictionary
      ansible.builtin.set_fact:
        subscription_resource_groups: >-
          {{
            subscription_resource_groups | default({}) |
            combine({
              item.item: item.resourcegroups | map(attribute='name') | list
            })
          }}
      loop: "{{ azure_resource_groups_info.results }}"
      vars:
        subscription_resource_groups: {}

    - name: Display the combined dictionary
      ansible.builtin.debug:
        msg: "Subscription Resource Groups: {{ subscription_resource_groups }}"