- hosts: localhost


  vars:
    subscription_info: []

  tasks:
    - name: get some info
      azure.azcollection.azure_rm_subscription_info:
        all: true
      register: azure_subscription_info

    - name: Create an array of subscription IDs
      ansible.builtin.set_fact:
        subscription_ids: "{{ azure_subscription_info.subscriptions | map(attribute='subscription_id') | list }}"

    - ansible.builtin.debug:
        msg: "Subscription IDs: {{ subscription_ids }}"

    # - name: get some info
    #   azure.azcollection.azure_rm_subscription_info:
    #     subscription_id: "{{ subscription_ids }}"
    #   register: azure_subscription_info

    - name: find all resources in the subscription
      include_tasks: resource_groups.yml
        vars: 
          subscription_id: "{{ item }}"
      loop: "{{ subscription_ids }}"

    # - name: Query all the resources in the resource group
    #   azure.azcollection.azure_rm_resourcegroup_info:
    #     subscription_id: "{{ item }}"
    #   register: azure_resource_groups_info
    #   loop: "{{ subscription_ids }}"

    # - ansible.builtin.debug:
    #     var: azure_resource_groups_info
    
    # - ansible.builtin.debug:
    #     msg: "{{ azure_resource_groups_info.results[0].resourcegroups}}"


    # - name: Get all resource groups in the subscription
    #   ansible.builtin.set_fact:
    #     resource_groups: "{{ azure_resource_groups_info.results[0].resourcegroups | map(attribute='name') | list }}"
    
    # - name: Get facts for one resource group
    #   azure.azcollection.azure_rm_resource_info:
    #     resource_group: "{{ item }}"
    #     provider: compute
    #     resource_type: virtualMachines
    #     api_version: 2024-11-01
    #   loop: "{{ resource_groups }}"
    #   register: all_vms_in_resouces

    - ansible.builtin.debug:
        var: subscription_info