- hosts: localhost


  vars:
    subscription_id: 695f969d-2418-491f-a6b3-bd0bf0c7cffb
    resource_group: openenv-njmbx

  tasks:
    - name: get some info
      azure.azcollection.azure_rm_subscription_info:
        all: true
      register: azure_subscription_info

    - name: Create an array of subscription IDs
      ansible.builtin.set_fact:
        subscription_ids: "{{ azure_subscription_info.subscriptions | map(attribute='subscription_id') | list }}"

    - ansible.builtin.debug:
        msg: "Subscription IDs: {{ subscription_ids }}