- hosts: localhost


  vars:
    subscription_info: []  # Initialize an empty list to store subscription info

  tasks:
    - name: return subscription IDs
      azure.azcollection.azure_rm_subscription_info:
        all: true
      register: azure_subscription_info

  # returning the list of subscriptions I can view from Azure, from there I create a Array of the subscription IDs as shown below.

    - name: Create an array of subscription IDs
      ansible.builtin.set_fact:
        subscription_ids: "{{ azure_subscription_info.subscriptions | map(attribute='subscription_id') | list }}"

    - name: debug the Subscription IDs variable
      ansible.builtin.debug:
        msg: "Subscription IDs: {{ subscription_ids }}"

# I need to loop over the Subscription IDs to find the Resource groups, due to the 1 to many relationship.
# Unfortunatly, Looping over blocks isn't supported in Ansible (which I agree is annoying), but to get around this, we can loop over the include tasks and set subscription id as "item"
    - name: find all resources in the subscription
      include_tasks: resource_groups.yml
      vars:
        subscription_id: "{{ item }}"
      loop: "{{ subscription_ids }}"

    - name: what is the subscription debug var at the end
      ansible.builtin.debug:
        var: subscription_info


    - name: what is the subscription debug var at the end
      ansible.builtin.debug:
        msg: "{{ subscription_info }}"
