- hosts: localhost

  tasks:
    - name: running a role within a collection
      ansible.builtin.include_role:
        name: demo.playpen.dns

    - name: include more tasks
      include_tasks: demo.playpen.playbooks.tasks.yml
      when: ansible_facts.ansible_system == "Linux"

- name: importing a playbook with variables
  ansible.builtin.import_playbook: demo.playpen.playbooks.example.yml
  vars:
    name: "playpen"