- hosts: localhost

  tasks:
    - name: running a role within a collection
      ansible.builtin.include_role:
        name: demo.playpen.dns

  - name: importing a playbook with variables
    ansible.builtin.import_playbook: demo.playpen.playbooks.example
    vars:
      name: "playpen"