# In recource groups I gather the information the same way we build out the subscription_ids, by using the map function to get the resource group names.
- name: Query all the resources in the resource group
  cazure.azcollection.azure_rm_resourcegroup_info:
    subscription_id: "{{ subscription_id }}"
  register: azure_resource_groups_info
      
- name: display the list of resource groups
  ansible.builtin.debug:
    var: azure_resource_groups_info

- name: Get all resource groups in the subscription
  ansible.builtin.set_fact:
    resource_groups: "{{ azure_resource_groups_info.resourcegroups | map(attribute='name') | list }}"

# Now that we have the resource groups, we can loop over them to find the VMs in each resource group.
- name: get all VMs allocated in resource groups
  ansible.builtin.include_tasks: find_vm.yml
  vars: 
    resource_group: "{{ resource_group }}"
  loop: "{{ resource_groups }}"
  loop_control:
    loop_var: resource_group
