- name: Update the 'voltron-net'
  hosts: localhost
  tasks:
    - name: Update voltron-net to true
      ansible.builtin.set_stats:
        data:
          domains: "{{ domains | combine({'gundam-nz': 'strike freedom'}) }}"
          gundam-nz': 'strike freedom'
          
    - name: Verify the updated variable
      ansible.builtin.debug:
        var: domains
