- name: Update the 'voltron-net' key in the 'domains' variable
  hosts: all
  vars:
    domains:
      voltron-net: false
      optimus-au: false
      gundam-nz: false
  tasks:
    - name: Update voltron-net to true
      ansible.builtin.set_stats:
        data:
          domains: "{{ domains | combine({'optimus-au': 'autobots'}) }}"

    - name: Verify the updated variable
      ansible.builtin.debug:
        var: domains
